// @ts-nocheck — import.meta.glob is Vite-only.
/**
 * Plugin registry for a dashin (Vite) project. Replaces dynamic
 * require()/import(`${var}`) with statically-analyzable import.meta.glob maps.
 * The `src/.dashin/dynamic/` tree is generated by the dashin generator
 * (run in vite.config buildStart) before these globs resolve.
 */
const indexEager = import.meta.glob("./.dashin/dynamic/index.js", {
  eager: true
})
const pluginsDataJson = import.meta.glob("./.dashin/dynamic/pluginsData.json", {
  eager: true
})
const pluginsDataTs = import.meta.glob("./.dashin/dynamic/pluginsData.ts", {
  eager: true
})
const dynamicLazy = import.meta.glob("./.dashin/dynamic/**/*/index.js")
// Local override/customized plugins (src/plugins/**).
const localPlugins = import.meta.glob("./plugins/**/index.{ts,tsx}")
// Plugin i18n bundles (installed @dashin-dev *plugin* packages), consumed
// synchronously. The dashin CORE package is excluded: it ships CommonJS and is
// served raw via this absolute-path glob (Vite can't CJS->ESM-interop it, so
// the browser throws "exports is not defined"), and its i18n init already runs
// through the optimized core bundle (TopBar/I18nMenu -> utils/i18n), so loading
// it here is both broken and redundant.
const pluginI18n = import.meta.glob(
  [
    "/node_modules/@dashin-dev/*/lib/utils/i18n/*.js",
    "!/node_modules/@dashin-dev/dashin/**"
  ],
  { eager: true }
)

const first = (m) => Object.values(m)[0]
const lazyKey = (p) => `./.dashin/dynamic/${p}/index.js`

export function getDynamicIndex() {
  const mod = first(indexEager)
  return (mod && mod.default) || {}
}
export function getPluginsDataJson() {
  const mod = first(pluginsDataJson)
  return (mod && mod.default) || []
}
export function getPluginsDataTs() {
  const mod = first(pluginsDataTs)
  return (mod && mod.data) || []
}
export function importPlugin(p) {
  const local =
    localPlugins[`./plugins/${p}/index.tsx`] ||
    localPlugins[`./plugins/${p}/index.ts`]
  const loader = local || dynamicLazy[lazyKey(p)]
  return loader
    ? loader()
    : Promise.reject(new Error(`plugin module not found: ${p}`))
}
export function hasPlugin(p) {
  return !!(
    localPlugins[`./plugins/${p}/index.tsx`] ||
    localPlugins[`./plugins/${p}/index.ts`] ||
    dynamicLazy[lazyKey(p)]
  )
}
export function requirePlugin(p) {
  const match = Object.keys(pluginI18n).find(k => k.includes(`/${p}.`))
  return match ? pluginI18n[match] : null
}
