/**
 * `bunadmin ai generate` — schema-aware admin generation.
 *
 *   introspect (ground truth) -> LLM (BYOK/cheap) -> VALIDATE -> emit schema file
 *
 * The emitted file is the same declarative input a human writes today
 * (see docs/pocketbase/example-posts.tsx), so it feeds the existing generator
 * with zero runtime changes.
 */
const fs = require("fs")
const path = require("path")
const { introspectPocketbase } = require("./introspect")
const { getProvider } = require("./provider")
const { validateColumns } = require("./validate")

function buildPrompt(schema) {
  return [
    "You generate a bunadmin admin table definition as STRICT JSON.",
    `Collection: "${schema.collection}".`,
    "Real fields (use ONLY these, do not invent fields):",
    JSON.stringify(schema.fields, null, 2),
    "",
    "Output JSON shape:",
    '{ "columns": [ { "title": string, "field": <one of the real field names>,',
    '  "type"?: "numeric", "lookup"?: { <value>: <label>, ... } } ] }',
    "Rules:",
    "- Exactly ONE column per field. Never duplicate a field.",
    "- `lookup` is a flat object mapping each allowed value to its own label.",
    '  For a select field with values ["Draft","Published"], lookup MUST be:',
    '    { "Draft": "Draft", "Published": "Published" }',
    '  (NOT { "value": ..., "label": ... }).',
    "- Use `type:\"numeric\"` only for number fields.",
    "- Include every field exactly once. Return ONLY JSON, no prose."
  ].join("\n")
}

function extractJson(text) {
  if (!text) return null
  // strip ```json ... ``` fences if present
  let t = text.trim()
  const fence = t.match(/```(?:json)?\s*([\s\S]*?)```/i)
  if (fence) t = fence[1].trim()
  try {
    return JSON.parse(t)
  } catch (e) {
    const m = t.match(/\{[\s\S]*\}/)
    try {
      return JSON.parse(m ? m[0] : t)
    } catch (e2) {
      return null
    }
  }
}

function emitSchemaFile(schema, columns, outDir) {
  const cols = columns
    .map(c => {
      const parts = [`title: t("${c.title || c.field}")`, `field: "${c.field}"`]
      if (c.field === "id") parts.push('editable: "never"')
      if (c.type) parts.push(`type: "${c.type}"`)
      if (c.lookup) parts.push(`lookup: ${JSON.stringify(c.lookup)}`)
      return `    { ${parts.join(", ")} }`
    })
    .join(",\n")

  const Name = schema.collection.charAt(0).toUpperCase() + schema.collection.slice(1)
  const file = `// AUTO-GENERATED by \`bunadmin ai generate\` — validated against the live schema.
import React, { createRef } from "react"
import { Table, TableHead, tableIcons, TableDefaultProps as DP, useTranslation } from "@xbuilder/bunadmin"
import { dataCtrl, editableCtrl } from "@xbuilder/bunadmin-source-pocketbase"

export default function ${Name}() {
  const { t } = useTranslation("table")
  const columns = [
${cols}
  ]
  return (
    <>
      <TableHead title="${Name}" />
      <Table
        tableRef={createRef()}
        title="${Name}"
        columns={columns}
        style={DP.style}
        icons={tableIcons({ theme: { bunadmin: { iconColor: "#8f9bb3" } } })}
        options={{ ...DP.options, filtering: true }}
        data={query => dataCtrl({ t, tableQuery: query, path: "${schema.collection}" })}
        editable={editableCtrl({ t, SchemaName: "${schema.collection}" })}
      />
    </>
  )
}
`
  const outPath = path.resolve(outDir, `${schema.collection}.generated.tsx`)
  fs.writeFileSync(outPath, file)
  return outPath
}

/**
 * @param opts { source, url, collection, token, out, mock }
 * @returns { errors?, outPath?, attempts, providerName }
 */
async function aiGenerate(opts) {
  const { source = "pocketbase", url, collection, token, out = ".", mock } = opts
  if (source !== "pocketbase")
    return { errors: `source "${source}" not supported in this spike` }
  if (!url || !collection)
    return { errors: "need --url and --collection" }

  // 1. Ground truth
  const schema = await introspectPocketbase(url, collection, token)

  // 2 + 3. Generate -> validate, retry once on hallucination
  const provider = getProvider(
    mock ? { ...process.env, BUNADMIN_AI_PROVIDER: "mock", __MOCK_RESPONSE: mock } : process.env
  )
  const prompt = buildPrompt(schema)
  let attempts = 0
  let result
  let lastErrors = []
  while (attempts < 2) {
    attempts++
    const raw = await provider.complete(
      attempts === 1
        ? prompt
        : prompt + "\n\nYour previous output was invalid:\n" + lastErrors.join("\n")
    )
    const parsed = extractJson(raw)
    result = validateColumns(parsed || {}, schema)
    if (result.ok) break
    lastErrors = result.errors
  }

  if (!result.ok)
    return {
      errors: `validation failed after ${attempts} attempt(s):\n - ${result.errors.join("\n - ")}`,
      attempts,
      providerName: provider.name
    }

  // 4. Emit
  const outPath = emitSchemaFile(schema, result.columns, out)
  return { outPath, attempts, providerName: provider.name }
}

module.exports = { aiGenerate, buildPrompt, extractJson, emitSchemaFile }
