/**
 * `bunadmin ai theme "<description>"` — schema-aware THEME generation.
 *
 *   prompt -> LLM (BYOK/cheap) -> VALIDATE (token contract) -> emit theme config
 *
 * Reuses the provider + retry pattern of ai/generate.js. Output is a tiny
 * validated { preset, mode, overrides } object consumed by applyPreset() at
 * runtime — the AI never writes CSS, only fills the constrained token contract.
 */
const fs = require("fs")
const path = require("path")
const { getProvider } = require("./provider")
const { extractJson } = require("./generate")
const {
  validateTheme,
  KNOWN_PRESETS,
  KNOWN_TOKENS
} = require("./theme-validate")

function buildThemePrompt(description) {
  return [
    "You configure a bunadmin admin THEME as STRICT JSON. You do NOT write CSS.",
    "Choose a base preset, a mode, and optional token overrides.",
    `presets: ${KNOWN_PRESETS.join(" | ")}`,
    "mode: light | dark",
    `overridable tokens (override ONLY these): ${KNOWN_TOKENS.join(", ")}`,
    "Token values: colors as #hex or rgb()/hsl()/linear-gradient(...); `radius` as a length (e.g. 12px).",
    "",
    "Output JSON shape (omit fields you don't change):",
    '{ "preset": "modern", "mode": "dark", "overrides": { "primary": "#7c3aed" } }',
    "Do NOT invent token names. Return ONLY JSON, no prose.",
    "",
    `User request: ${description}`
  ].join("\n")
}

function emitThemeFile(theme, outDir) {
  const file = `// AUTO-GENERATED by \`bunadmin ai theme\` — validated against the token contract.
// Consume at runtime: import { applyPreset } from "@xbuilder/bunadmin";
//   applyPreset(theme.preset, theme.mode, theme.overrides)
export const theme = ${JSON.stringify(theme, null, 2)} as const
export default theme
`
  const outPath = path.resolve(outDir, "bunadmin.theme.ts")
  fs.writeFileSync(outPath, file)
  return outPath
}

/**
 * @param opts { description, out, mock }
 * @returns { errors?, outPath?, theme?, attempts, providerName }
 */
async function aiTheme(opts) {
  const { description, out = ".", mock } = opts
  if (!description) return { errors: 'need a description, e.g. ai theme "dark, purple accent"' }

  const provider = getProvider(
    mock ? { ...process.env, BUNADMIN_AI_PROVIDER: "mock", __MOCK_RESPONSE: mock } : process.env
  )
  const prompt = buildThemePrompt(description)
  let attempts = 0
  let result
  let lastErrors = []
  while (attempts < 2) {
    attempts++
    const raw = await provider.complete(
      attempts === 1 ? prompt : prompt + "\n\nPrevious output invalid:\n" + lastErrors.join("\n")
    )
    result = validateTheme(extractJson(raw) || {})
    if (result.ok) break
    lastErrors = result.errors
  }

  if (!result.ok)
    return {
      errors: `theme validation failed after ${attempts} attempt(s):\n - ${result.errors.join("\n - ")}`,
      attempts,
      providerName: provider.name
    }

  const outPath = emitThemeFile(result.theme, out)
  return { outPath, theme: result.theme, attempts, providerName: provider.name }
}

module.exports = { aiTheme, buildThemePrompt, emitThemeFile }
