const path = require("path")
const fs = require("fs")
const del = require("del")
const {
  findPlugins,
  getPlugins,
  getPluginNames
} = require("./lib/utils/node/plugin-action")

/**
 * Prepare bunadmin plugins data to `.bunadmin/dynamic/`, `plugins/` directory,
 * generate the data file (menu, schema) `dynamic/pluginsData.json` to `.bunadmin/`,
 * generate the index file (export from node_modules) `[name]/index.js` to
 * `dynamic/[plugin]/[name]/index.js`.
 * generate the data file (menu, schema) `pluginsData.ts` to `.bunadmin/dynamic/`,
 * @param packagePath {string}
 * @param modulesPath {string}
 * @param dynamicPath {string}
 * @param pluginsPath {string}
 * @return {boolean}
 */
module.exports = async ({
  packagePath,
  modulesPath,
  dynamicPath,
  pluginsPath
}) => {
  /**
   * Prepare plugins START
   */
  console.info("prepare bunadmin plugins")

  /**
   * Generate pluginsData.json START
   */
  console.info("preparing...")

  /**
   * Check, recreate directory .bunadmin/dynamic
   */
  if (fs.existsSync(dynamicPath)) {
    await del(dynamicPath)
  }

  const dotBunadminPath = dynamicPath.replace("dynamic", "")
  if (!fs.existsSync(dotBunadminPath)) {
    fs.mkdirSync(dotBunadminPath)
  }
  if (!fs.existsSync(dynamicPath)) {
    fs.mkdirSync(dynamicPath)
  }

  // Find plugins in package.json
  const pluginNames = getPluginNames(packagePath)
  const pluginsData = getPlugins(pluginNames)

  /**
   * Generate `index.js` in `.bunadmin/dynamic/`
   * for dynamically importing packages from package.json
   */
  let exportLine = ""
  pluginNames.map(pluginName => {
    exportLine += `  "${pluginName}": require("${pluginName}"),\n`
  })
  const indexJsContent = `/**
 * This file is automatically generated by bunadmin,
 * please do not modify this file.
 */
export default {\n  ${exportLine}}`

  fs.writeFile(`${dynamicPath}/index.js`, indexJsContent, e => {
    if (e) console.error("cannot generating `${dynamicPath}/index.js`: " + e)
  })

  /**
   * Generate `pluginsData.ts` in `.bunadmin/dynamic/`
   * for dynamically importing packages from custom plugins
   */
  const customPluginsPaths = findPlugins(pluginsPath)
  const relativePath = path
    .relative(path.dirname(dynamicPath), path.dirname(pluginsPath))
    .replaceAll(/\\/g, "/") // Fixing the PATH on Windows

  let importLine = ""
  let arrayLine = ""
  customPluginsPaths.map((path, i) => {
    let name = path.replaceAll(/\\/g, "/") // Fixing the PATH on Windows
    name = name.replace(/.*\/(.*)/g, "$1")

    const varName = `data_${i + 1}`
    importLine += `
import { initData as ${varName} } from "../${relativePath}/plugins/${name}"`
    const spl = i + 1 === customPluginsPaths.length ? "" : ", "
    arrayLine += `...${varName}${spl}`
  })
  const tsContent = `/**
 * This file is automatically generated by bunadmin,
 * please do not modify this file.
 */
import { IPluginData } from "@xbuilder/bunadmin"
${importLine}

export const data: IPluginData[] = [${arrayLine}]
`
  fs.writeFile(`${dynamicPath}/pluginsData.ts`, tsContent, e => {
    if (e) console.error("cannot generating pluginsData.ts: " + e)
  })

  /**
   * Generate plugin schemas ([plugin]/[group]/[name].js)
   * form plugin files (in `node_modules`)
   */
  pluginNames.map(async pluginName => {
    if (typeof modulesPath !== "string") throw "modulesPath is required!"
    const pathItem = `${modulesPath}/${pluginName}`

    if (pathItem.indexOf("node_modules") < 0) {
      throw "modulesPath needs to contain `node_modules`!"
    }

    let plugin
    try {
      plugin = require(pathItem)
      if (!plugin || !plugin.initData || !plugin.initData.data) return
    } catch (e) {
      console.error("\n*************")
      console.error(
        "Failed to process bunadmin plugin, there may be two reasons: " + e
      )
      console.error("1. " + e)
      console.error(
        "2. cannot find 'initData' in the plugin, please export or check: " +
          pathItem
      )
      console.error("*************\n")
    }

    /**
     * Generating plugin files under `dynamic/`
     * mkdir directories [plugin], [plugin]/[group]
     * create files [plugin]/[group]/[name].js
     */
    try {
      if (!plugin) return
      let fileName = pathItem.replaceAll(/\\/g, "/") // Fixing the PATH on Windows
      fileName = fileName.replace(/.*\//g, "")
      /**
       * Recreate directory dynamic/[plugin]
       */
      const savePluginPath = path.resolve(dynamicPath, fileName)
      if (!fs.existsSync(savePluginPath)) {
        fs.mkdirSync(savePluginPath)
      }
      plugin.initData.data.map(async dataItem => {
        if (dataItem["ignore_schema"] || !dataItem["name"]) return
        /**
         * Recreate directory dynamic/[plugin]/[name]
         */
        const saveNamePath = path.resolve(savePluginPath, dataItem["name"])
        if (!fs.existsSync(saveNamePath)) {
          fs.mkdirSync(saveNamePath)
        }
        const saveNameContent = `export { default } from "${pluginName}/lib/${dataItem["name"]}"`
        fs.writeFile(`${saveNamePath}/index.js`, saveNameContent, e => {
          if (e) console.error("could not generate plugin schema: " + e)
        })

        const saveIndexPath = path.resolve(dynamicPath, `${fileName}/index.js`)
        const saveIndexContent = `export * from "${pluginName}"`
        fs.writeFile(saveIndexPath, saveIndexContent, e => {
          if (e) console.error("could not generate plugin index.js: " + e)
        })
      })
    } catch (e) {
      console.error("could not generate pluginSchema: " + e)
    }
  })

  const name = "pluginsData.json"
  const savePath = path.resolve(dynamicPath, name)
  console.log("savePath", savePath)
  fs.writeFile(savePath, JSON.stringify(pluginsData), "utf8", () => {
    /**
     * Prepare plugins END
     */
    console.info("bunadmin plugins data generated successfully")
  })
  /**
   * Generate pluginsData.json END
   */

  return true
}
