const path = require("path")
const fs = require("fs")
const del = require("del")
const {
  findPlugins,
  getPlugins,
  getPluginNames
} = require("./lib/utils/node/plugin-action")

/**
 * Prepare bunadmin plugins data to `.bunadmin/dynamic/`, `plugins/` directory,
 * generate the data file (menu, schema) `dynamic/pluginsData.json` to `.bunadmin/`,
 * generate the index file (export from node_modules) `[name]/index.js` to
 * `dynamic/[plugin]/[name]/index.js`.
 * generate the data file (menu, schema) `pluginsData.ts` to `.bunadmin/dynamic/`,
 * @param packagePath {string}
 * @param dynamicPath {string}
 * @param pluginsPath {string}
 * @return {boolean}
 */
module.exports = async ({ packagePath, dynamicPath, pluginsPath }) => {
  /**
   * Prepare plugins START
   */
  console.info("prepare bunadmin plugins")

  /**
   * Generate pluginsData.json START
   */
  console.info("preparing...")

  /**
   * Check, recreate directory .bunadmin/dynamic
   */
  if (fs.existsSync(dynamicPath)) {
    await del(dynamicPath)
  }

  const dotBunadminPath = dynamicPath.replace("dynamic", "")
  if (!fs.existsSync(dotBunadminPath)) {
    fs.mkdirSync(dotBunadminPath)
  }
  if (!fs.existsSync(dynamicPath)) {
    fs.mkdirSync(dynamicPath)
  }

  // Find plugins in packagePath
  const pluginNames = getPluginNames(packagePath)
  const pluginsData = getPlugins(pluginNames)

  /**
   * Generate `index.ts` in `.bunadmin/dynamic/`
   */
  let exportLine = ""
  pluginNames.map(pluginName => {
    exportLine += `  "${pluginName}": require("${pluginName}"),\n`
  })
  const indexJsContent = `/**
 * This file is automatically generated by bunadmin,
 * please do not modify this file.
 */
export default {\n  ${exportLine}}`

  fs.writeFile(`${dynamicPath}/index.js`, indexJsContent, e => {
    if (e) console.error("cannot generating `${dynamicPath}/index.js`: " + e)
  })

  /**
   * Generate `pluginsData.ts` in `.bunadmin/dynamic/`
   */
  const customPluginsPaths = findPlugins(pluginsPath)
  const relativePath = path
    .relative(path.dirname(dynamicPath), path.dirname(pluginsPath))
    .replaceAll(/\\/g, "/") // Fixing the PATH on Windows

  let importLine = ""
  let arrayLine = ""
  customPluginsPaths.map((path, i) => {
    let name = path.replaceAll(/\\/g, "/") // Fixing the PATH on Windows
    name = name.replace(/.*\/(.*)/g, "$1")

    const varName = `data_${i + 1}`
    importLine += `
import { initData as ${varName} } from "../${relativePath}/plugins/${name}"`
    const spl = i + 1 === customPluginsPaths.length ? "" : ", "
    arrayLine += `...${varName}${spl}`
  })
  const tsContent = `/**
 * This file is automatically generated by bunadmin,
 * please do not modify this file.
 */
import { IPluginData } from "@xbuilder/bunadmin"
${importLine}

export const data: IPluginData[] = [${arrayLine}]
`
  fs.writeFile(`${dynamicPath}/pluginsData.ts`, tsContent, e => {
    if (e) console.error("cannot generating pluginsData.ts: " + e)
  })

  const name = "pluginsData.json"
  const savePath = path.resolve(dynamicPath, name)
  console.log("savePath", savePath)
  fs.writeFile(savePath, JSON.stringify(pluginsData), "utf8", () => {
    /**
     * Prepare plugins END
     */
    console.info("bunadmin plugins data generated successfully")
  })
  /**
   * Generate pluginsData.json END
   */

  return true
}
