#!/usr/bin/env bash
# Regenerate docs/CONTRIBUTORS.md from git history scoped to docs/.
# Run from repo root:  sh scripts/gen-docs-contributors.sh
set -euo pipefail

OUT="docs/CONTRIBUTORS.md"

{
  echo "# Docs Contributors"
  echo
  echo "People who have contributed to \`docs/\`, by commit count."
  echo "_Auto-generated by \`scripts/gen-docs-contributors.sh\` — do not edit by hand._"
  echo
  # -s summary, -n by count, -e show email; scoped to docs/
  git shortlog -sne HEAD -- docs/ | sed -E 's/^[[:space:]]*([0-9]+)[[:space:]]+(.*)$/- **\1** — \2/'
  echo
  echo "_Generated $(date -u +%Y-%m-%d)._"
} > "$OUT"

echo "✓ wrote $OUT"
