// @ts-nocheck — import.meta.glob is Vite-only.
/**
 * Plugin registry for a bunadmin (Vite) project. Replaces dynamic
 * require()/import(`${var}`) with statically-analyzable import.meta.glob maps.
 * The `src/.bunadmin/dynamic/` tree is generated by the bunadmin generator
 * (run in vite.config buildStart) before these globs resolve.
 */
const indexEager = import.meta.glob("./.bunadmin/dynamic/index.js", {
  eager: true
})
const pluginsDataJson = import.meta.glob("./.bunadmin/dynamic/pluginsData.json", {
  eager: true
})
const pluginsDataTs = import.meta.glob("./.bunadmin/dynamic/pluginsData.ts", {
  eager: true
})
const dynamicLazy = import.meta.glob("./.bunadmin/dynamic/**/*/index.js")
// Local override/customized plugins (src/plugins/**).
const localPlugins = import.meta.glob("./plugins/**/index.{ts,tsx}")
// Plugin i18n bundles (installed @xbuilder packages), consumed synchronously.
const pluginI18n = import.meta.glob(
  "/node_modules/@xbuilder/*/lib/utils/i18n/*.js",
  { eager: true }
)

const first = (m) => Object.values(m)[0]
const lazyKey = (p) => `./.bunadmin/dynamic/${p}/index.js`

export function getDynamicIndex() {
  const mod = first(indexEager)
  return (mod && mod.default) || {}
}
export function getPluginsDataJson() {
  const mod = first(pluginsDataJson)
  return (mod && mod.default) || []
}
export function getPluginsDataTs() {
  const mod = first(pluginsDataTs)
  return (mod && mod.data) || []
}
export function importPlugin(p) {
  const local =
    localPlugins[`./plugins/${p}/index.tsx`] ||
    localPlugins[`./plugins/${p}/index.ts`]
  const loader = local || dynamicLazy[lazyKey(p)]
  return loader
    ? loader()
    : Promise.reject(new Error(`plugin module not found: ${p}`))
}
export function hasPlugin(p) {
  return !!(
    localPlugins[`./plugins/${p}/index.tsx`] ||
    localPlugins[`./plugins/${p}/index.ts`] ||
    dynamicLazy[lazyKey(p)]
  )
}
export function requirePlugin(p) {
  const match = Object.keys(pluginI18n).find(k => k.includes(`/${p}.`))
  return match ? pluginI18n[match] : null
}
