import { test, expect } from "@playwright/test"
import { resolve } from "node:path"
const url = "/e2e/fixtures/reliability.html"

test("real IndexedDB auth: rejection, rollback and edited retry leave no partial identity", async ({ page }) => {
  const errors: string[] = []
  page.on("pageerror", error => errors.push(error.message))
  await page.goto(url)
  for (const scenario of ["401", "403", "network", "timeout", "malformed", "storage", "mid-write"]) {
    await page.getByLabel("Login scenario").selectOption(scenario)
    await page.getByRole("button", { name: "Sign in", exact: true }).click()
    await expect(page.getByRole("alert")).toBeVisible()
    await expect(page.getByRole("button", { name: "Sign in", exact: true })).toBeEnabled()
    expect(await page.evaluate(async () => {
      const f = (window as any).fixture
      return [await f.users.count(), await f.settings.count(), f.navigated, localStorage.getItem("fixture-token")]
    })).toEqual([0, 0, 0, null])
  }
  await page.getByLabel("Username").fill("edited@example.test")
  await expect(page.getByRole("alert")).toHaveCount(0)
  await page.getByLabel("Login scenario").selectOption("success")
  await page.getByRole("button", { name: "Sign in", exact: true }).click()
  await expect.poll(() => page.evaluate(() => (window as any).fixture.navigated)).toBe(1)
  expect(await page.evaluate(async () => [(await (window as any).fixture.users.toArray())[0].username, await (window as any).fixture.settings.count()])).toEqual(["edited@example.test", 2])
  expect(errors).toEqual([])
})

test("orders discard old failures and latest failure can be refreshed", async ({ page }) => {
  await page.goto(url)
  const orders = page.getByRole("region", { name: "Orders", exact: true })
  await expect.poll(() => page.evaluate(() => (window as any).fixture.requests.length)).toBe(1)
  await orders.getByRole("textbox", { name: "Search" }).fill("B")
  await expect.poll(() => page.evaluate(() => (window as any).fixture.requests.length)).toBe(2)
  await page.evaluate(() => (window as any).fixture.requests[1].reject(new Error("latest failure")))
  await expect(orders.getByRole("alert")).toContainText("latest failure")
  await page.evaluate(() => (window as any).fixture.requests[0].reject(new Error("stale failure")))
  await expect(orders.getByRole("alert")).not.toContainText("stale")
  await orders.getByRole("button", { name: "Refresh Data" }).click()
  await expect.poll(() => page.evaluate(() => (window as any).fixture.requests.length)).toBe(3)
  await page.evaluate(() => (window as any).fixture.requests[2].resolve({ data: [{ number: "ORDER-3" }], page: 0, totalCount: 1 }))
  await expect(orders.getByText("ORDER-3")).toBeVisible()
  await expect(orders.getByRole("alert")).toHaveCount(0)
})

test("products preserve explicit IDs across pages and retry only the failed item", async ({ page }) => {
  await page.goto(url)
  const products = page.getByRole("region", { name: "Products", exact: true })
  await products.getByRole("checkbox").nth(1).check()
  await products.getByRole("button", { name: "Next Page" }).click()
  await products.getByRole("checkbox").nth(1).check()
  await products.getByRole("button", { name: "Delete", exact: true }).click()
  await expect(products.getByRole("alert")).toContainText("product-3")
  expect(await page.evaluate(() => (window as any).fixture.deletes)).toEqual(["product-1", "product-3"])
  await page.evaluate(() => { (window as any).fixture.deleteFails = false })
  await products.getByRole("button", { name: "Delete", exact: true }).click()
  expect(await page.evaluate(() => (window as any).fixture.deletes)).toEqual(["product-1", "product-3", "product-3"])
})

for (const locale of ["en", "zh"]) test(`${locale}: short mobile viewport, menu/last column/drawer keyboard path and axe`, async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 480 })
  await page.goto(`${url}?locale=${locale}`)
  const catalog = page.getByRole("button", { name: "Catalog", exact: true })
  await catalog.click()
  await page.getByRole("button", { name: "Item 18", exact: true }).scrollIntoViewIfNeeded()
  await expect(page.getByRole("button", { name: "Item 18", exact: true })).toBeInViewport()
  await catalog.click()
  expect(await page.getByRole("button", { name: "Item 18", exact: true, includeHidden: true }).getAttribute("tabindex")).toBe("-1")
  await page.getByRole("button", { name: "Toggle sidebar" }).click()
  await catalog.focus()
  await catalog.press("ArrowRight")
  await expect(page.getByRole("menuitem", { name: "Item 1", exact: true })).toBeFocused()
  for (let index = 0; index < 17; index++) await page.keyboard.press("ArrowDown")
  await expect(page.getByRole("menuitem", { name: "Item 18", exact: true })).toBeFocused()
  await expect(page.getByRole("menuitem", { name: "Item 18", exact: true })).toBeInViewport()
  await page.keyboard.press("Escape")
  await expect(page.getByRole("menu")).toHaveCount(0)
  await expect(catalog).toBeFocused()
  const products = page.getByRole("region", { name: "Products", exact: true })
  const last = products.getByRole("columnheader", { name: "warehouse" })
  await last.scrollIntoViewIfNeeded()
  await expect(last).toBeInViewport()
  await page.addScriptTag({ path: resolve(process.cwd(), "../../node_modules/axe-core/axe.min.js") })
  const listViolations = await page.evaluate(async () => (await (window as any).axe.run({ include: [["[aria-label='Products']"], ["[aria-label='Orders']"], ["nav"]] }, { runOnly: { type: "tag", values: ["wcag2a", "wcag2aa"] } })).violations.map((item: any) => ({ id: item.id, nodes: item.nodes.map((node: any) => node.target) })))
  expect(listViolations).toEqual([])
  await page.getByRole("button", { name: "Open product" }).click()
  const dialog = page.getByRole("dialog")
  const name = dialog.getByRole("textbox", { name: "name", exact: true })
  await name.fill("Edited product")
  await expect(name).toBeFocused()
  const violations = await page.evaluate(async () => (await (window as any).axe.run(document.querySelector('[role="dialog"]'), { runOnly: { type: "tag", values: ["wcag2a", "wcag2aa"] } })).violations.map((item: any) => ({ id: item.id, nodes: item.nodes.map((node: any) => node.target) })))
  expect(violations).toEqual([])
  const save = dialog.getByRole("button", { name: locale === "zh" ? "保存" : "Save", exact: true })
  await save.click()
  await expect(dialog.getByRole("alert")).toHaveText("Synthetic save failure")
  await expect(name).toHaveValue("Edited product")
  await save.focus(); await page.keyboard.press("Tab")
  await expect(dialog.getByRole("button", { name: locale === "zh" ? "关闭" : "Close", exact: true })).toBeFocused()
  await page.keyboard.press("Escape")
  await expect(dialog).toHaveCount(0)
  await expect(page.getByRole("button", { name: "Open product" })).toBeFocused()
})

test("nested preview failures restore focus and preserve the parent draft", async ({ page }) => {
  await page.goto(url)
  await page.getByRole("button", { name: "Open product" }).click()
  const parent = page.getByRole("dialog").first()
  await parent.getByRole("textbox", { name: "name", exact: true }).fill("Parent unsaved draft")
  const card = parent.getByRole("button", { name: "Related product" })
  await card.focus(); await page.keyboard.press("Enter")
  await expect(page.getByRole("dialog")).toHaveCount(2)
  const preview = page.getByRole("dialog").nth(1)
  await preview.getByRole("button", { name: "Edit", exact: true }).click()
  await expect(page.getByRole("dialog")).toHaveCount(3)
  await page.getByRole("dialog").nth(2).getByRole("button", { name: "Save", exact: true }).click()
  await expect(page.getByRole("dialog").nth(2).getByRole("alert")).toHaveText("Synthetic nested save failure")
  await page.keyboard.press("Escape")
  await expect(page.getByRole("dialog")).toHaveCount(2)
  await expect(preview.getByRole("button", { name: "Edit", exact: true })).toBeFocused()
  await page.keyboard.press("Escape")
  await expect(page.getByRole("dialog")).toHaveCount(1)
  await expect(card).toBeFocused()
  await expect(parent.getByRole("textbox", { name: "name", exact: true })).toHaveValue("Parent unsaved draft")
})

test("closing unchanged order preview does not query; successful save reloads exactly once", async ({ page }) => {
  await page.goto(url)
  const region = page.getByRole("region", { name: "Order lifecycle", exact: true })
  await region.getByText("ORDER-C", { exact: true }).click()
  await page.getByRole("dialog").getByRole("button", { name: "Close", exact: true }).click()
  expect(await page.evaluate(() => (window as any).crudFixture.loads)).toBe(1)
  await region.getByRole("button", { name: "Edit", exact: true }).click()
  await page.getByRole("dialog").getByRole("textbox", { name: "number" }).fill("ORDER-EDITED")
  await page.getByRole("dialog").getByRole("button", { name: "Save", exact: true }).click()
  await expect(page.getByRole("dialog")).toHaveCount(0)
  await expect.poll(() => page.evaluate(() => (window as any).crudFixture)).toEqual({ loads: 2, saves: 1 })
})
